name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install project dependencies
      - run: npm install

      # Build the project
      - run: npm run build

      # Run tests
      - run: npm run test:ci

      # Create a new version
      - run: npm run version

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PREFERENCE_LIST_REACT }}'
          channelId: live
          projectId: preference-list-react
