name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build application
        run: bun run build

      - name: Run Jest tests
        run: bun run test

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v3
        env:
          CYPRESS_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          CYPRESS_FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          CYPRESS_FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
        with:
          start: bun start # Start your app
          wait-on: 'http://localhost:3000' # Wait for your app to start