name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install project dependencies
      - run: npm install

      # Build the project
      - run: npm run build

      # Run jest tests
      - run: npm run test

      # Run Cypress tests with environment variables
      - name: Run Cypress tests
        run: npm run cypress:run -- --env FIREBASE_PROJECT_ID=${{ env.FIREBASE_PROJECT_ID }},FIREBASE_PRIVATE_KEY=${{ env.FIREBASE_PRIVATE_KEY }},FIREBASE_CLIENT_EMAIL=${{ env.FIREBASE_CLIENT_EMAIL }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

      # Create a new version
      - run: npm run version

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PREFERENCE_LIST_REACT }}'
          channelId: live
          projectId: preference-list-react
